/* AI 헬퍼 학생응답 제출 모듈 */
(() => {
  'use strict';
  const COLLECTOR_ENDPOINT = 'https://script.google.com/macros/s/AKfycbyO09T9tQX8Ut_z3EMhvhGW3s9ck2GJzEsnNIFU-lWxkFvK4DwwgfKpr081LwcRf_kMUg/exec';
  const SCHEMA_VERSION = '1.0';
  const SOURCE_SITE = 'https://helper83.github.io/industry-job-pick/';
  const $ = id => document.getElementById(id);
  const val = id => $(id)?.value ?? '';
  const safe = v => { try { return JSON.parse(JSON.stringify(v)); } catch { return null; } };
  function submissionId(){ return globalThis.crypto?.randomUUID?.() || `sub_${Date.now()}_${Math.random().toString(36).slice(2,12)}`; }
  function snapshot(){ try { if (typeof state !== 'undefined') return safe(state) || {}; } catch {} return {}; }
  function calcSnapshot(){ try { if (typeof computed !== 'undefined') return safe(computed); } catch {} return null; }
  function payload(){ const s=snapshot(); return { action:'submit_response', schemaVersion:SCHEMA_VERSION, submissionId:submissionId(), appVersion:(document.title.match(/V[\d.]+/i)||['unknown'])[0], sourceSite:SOURCE_SITE, pageUrl:location.href, consent:true, profile:{ studentLabel:val('studentId'), grade:val('grade'), major1:val('major1'), major2:val('major2'), transfer:val('transfer'), transferMajor:val('transferMajorText'), gradStatus:val('gradStatus'), gradMajor:val('gradMajorText'), gradResearch:val('gradResearch'), targetDate:val('targetDate'), sector:val('sector'), region:val('region'), minSalary:val('minSalary'), shift:val('shift'), travel:val('travel'), employment:val('employment'), companySize:val('companySize') }, answers:Array.isArray(s.answers)?s.answers.slice(0,57):[], skills:Array.isArray(s.skills)?s.skills:[], experience:s.exp||{}, credentials:s.credential||{}, industryInterest:Array.isArray(s.industryInterest)?s.industryInterest:[], results:calcSnapshot(), fullState:s }; }
  function install(){ const page=document.querySelector('[data-page="results"]')||document.querySelector('main')||document.querySelector('.app'); if(!page||document.getElementById('studentSubmitPanel'))return; const box=document.createElement('section'); box.id='studentSubmitPanel'; box.className='panel no-print'; box.innerHTML=`<h2>응답 제출</h2><p class="muted">입력한 진로·취업 탐색 자료와 추천결과를 운영자의 Google Sheets에 제출할 수 있습니다. 제출은 선택사항입니다.</p><label style="display:flex;gap:8px;align-items:flex-start;margin:12px 0"><input type="checkbox" id="submitConsent" style="width:20px;height:20px;margin-top:2px"><span>입력한 자료의 제출에 동의합니다. 학번·주민등록번호 등 불필요한 민감정보는 입력하지 않습니다.</span></label><button class="btn primary" type="button" id="submitStudentData" disabled style="width:100%;min-height:46px">응답 제출</button><p id="submitStudentStatus" class="tiny" role="status" aria-live="polite"></p><iframe name="studentSubmitFrame" id="studentSubmitFrame" hidden></iframe><form method="post" action="${COLLECTOR_ENDPOINT}" target="studentSubmitFrame" id="studentSubmitForm" hidden><textarea name="payload" id="studentSubmitPayload"></textarea></form>`; const actions=page.querySelector('.step-actions'); actions?page.insertBefore(box,actions):page.appendChild(box); const consent=$('submitConsent'),btn=$('submitStudentData'),status=$('submitStudentStatus'),form=$('studentSubmitForm'),field=$('studentSubmitPayload'),frame=$('studentSubmitFrame'); consent.onchange=()=>btn.disabled=!consent.checked; let waiting=false; window.addEventListener('message',e=>{ if(!waiting||e.source!==frame.contentWindow||e.data?.type!=='AI_HELPER_SUBMIT')return; waiting=false; if(e.data.ok){status.textContent='제출이 완료되었습니다.';status.style.color='#18794e';btn.textContent='제출 완료';btn.disabled=true;consent.disabled=true;}else{status.textContent=e.data.message||'제출 중 오류가 발생했습니다.';status.style.color='#b42318';btn.disabled=false;btn.textContent='다시 제출';}}); btn.onclick=()=>{ if(!consent.checked||waiting)return; const p=payload(); const answered=(p.answers||[]).filter(v=>v!==''&&v!=null).length; if(!answered){status.textContent='개인특성 문항에 응답한 뒤 제출해 주세요.';status.style.color='#b42318';return;} field.value=JSON.stringify(p);waiting=true;btn.disabled=true;btn.textContent='제출 중…';status.textContent='전송 중입니다.';status.style.color='';form.submit(); setTimeout(()=>{if(!waiting)return;waiting=false;btn.disabled=false;btn.textContent='다시 제출';status.textContent='서버 응답이 지연되고 있습니다. 네트워크를 확인해 주세요.';status.style.color='#b42318';},15000); }; }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();